#
# (c) Copyright 2015-2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Designate PowerDNS Database
---

# Note designate PowerDNS backend DB schema has changed for
# pdns4 backend driver corresponding to PowerDNS v4+.
# This change is not handled by DB migration scripts.
# Upstream bug: https://bugs.launchpad.net/designate/+bug/1746836
# Our strategy mirrors what is being done in devstack.
# On finding old schema we remove the tables and recreate it.

- name: powerdns-post-configure | db_configure | Check if DB is empty
  become: yes
  command: mysql -e
          "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
          WHERE TABLE_SCHEMA = 'designate_pdns';"
  register: is_db_empty_result
  ignore_errors: True

- name: powerdns-post-configure | db_configure | Set fact db_empty
  set_fact:
    designate_pdns_db_empty: "{{ is_db_empty_result.stdout_lines[1] == '0' }}"

# Note: column 'designate_id' only exists in Old DB Schema
- name: powerdns-post-configure | db_configure | Check if DB has old schema
  become: yes
  command: mysql -e
          "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
          WHERE TABLE_SCHEMA = 'designate_pdns' AND
          TABLE_NAME = 'domains' AND COLUMN_NAME = 'designate_id';"
  register: is_old_schema_result
  ignore_errors: True

- name: powerdns-post-configure | db_configure | Set fact old_schema
  set_fact:
    designate_pdns_old_schema:
      "{{ is_old_schema_result.stdout_lines[1] == '1' }}"

- name: powerdns-post-configure | db_configure | Drop designate_pdns DB tables
  become: yes
  command: mysql designate_pdns -e "DROP TABLE IF EXISTS {{ item }};"
  with_items:
    - comments
    - cryptokeys
    - domainmetadata
    - records
    - supermasters
    - tsigkeys
    - domains
  run_once_per: verb_hosts.FND_MDB
  when: designate_pdns_old_schema|bool

- name: powerdns-post-configure | db_configure | Copy the pdns4 SQL file
  become: yes
  copy:
    src: backend-pdns4-mysql-db.sql
    dest: /tmp/backend-pdns4-mysql-db.sql
    owner: root
    group: root
    mode: 0740
  run_once_per: verb_hosts.FND_MDB
  when: designate_pdns_old_schema|bool or designate_pdns_db_empty|bool

- name: powerdns-post-configure | db_configure | Recreate designate_pdns tables
  become: yes
  shell: mysql designate_pdns < /tmp/backend-pdns4-mysql-db.sql
  run_once_per: verb_hosts.FND_MDB
  when: designate_pdns_old_schema|bool or designate_pdns_db_empty|bool
