#
# (c) Copyright 2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# This file will contain the default values for the designate-producer service
---
designate_component: designate-producer

# packages listed here will be installed by designate-common | install
designate_required_packages:
  - libmysqlclient18

# packages listed here will trigger a restart of the service when updated
designate_producer_restart_packages:
  - libmysqlclient18

# producer.conf
## [service:producer]

## [coordination]
designate_backend_url: "zookeeper://{% for node in DES_PDR.consumes_FND_ZOO.members.private %}{{ node.host }}:{{ node.port }}{% if not loop.last %},{% endif %}{% endfor %}"

#designate_pool_id:  794ccc2c-d751-44fe-b57f-8894c9f5c842
