#
# (c) Copyright 2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Configure the designate-worker service
---
- include: ../../designate-common/tasks/_set_directories.yml
  vars:
    install_package_result: "{{ ardana_notify_designate_worker_venv_changed }}"

- include: ../../designate-common/tasks/configure.yml

- name: "designate-worker | configure | Notify on rootwrap change"
  shell: echo "notify rootwrap change"
  when: rootwrap_changed
  register: ardana_notify_designate_worker_restart_required

- include: ../../designate-common/tasks/_write_conf.yml
  src: "../../designate-worker/templates/worker.conf.j2"
  dest: "worker.conf"

# write_conf_result is set within the _write_conf.yml task, and
# is still available for us once the _write_conf task completes.
- name: "designate-worker | configure | Notify on worker.conf change"
  shell: echo "notify change"
  when: write_conf_result.changed
  register: ardana_notify_designate_worker_restart_required

- include: ../../designate-common/tasks/_write_conf.yml
  src: "../../designate-worker/templates/pools.yaml.j2"
  dest: "pools.yaml"

# write_conf_result is set within the _write_conf.yml task, and
# is still available for us once the _write_conf task completes.
- name: "designate-worker | configure | Notify on pools.yaml change"
  shell: echo "notify change"
  when: write_conf_result.changed
  register: ardana_notify_designate_worker_restart_required

- name: "designate-worker | configure | Apply template: {{ item }}"
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: "{{ designate_service_conf_dir }}/{{ item }}"
    owner: "{{ designate_system_user }}"
    group: "{{ designate_system_group }}"
    mode: 0640
  with_items:
    - "worker-logging.conf"
  register: ardana_notify_designate_worker_restart_required

- name: "designate-worker | configure | Write rndc key file"
  become: yes
  template:
    src: "rndc.key.j2"
    dest: "{{ designate_rndc_key_file }}"
    owner: "{{ designate_system_user }}"
    group: "{{ designate_system_group }}"
    mode: 0600
  when: ( 'FND_BND' in verb_hosts )
  register: ardana_notify_designate_worker_restart_required

- name: "designate-worker | configure | set designate log file ownership"
  become: yes
  file:
    path: "{{ designate_log_file_location }}/{{ item }}"
    owner: "{{ designate_system_user }}"
    group: "{{ designate_log_file_group }}"
    mode: 0640
    state: touch
  with_items:
    - designate-worker.log
    - designate-worker-json.log
